### ISSUE TITLE
The plans due to new DT Select extension

### ISSUE THREAD

**Issue by ashl1** [toXXIc/datatables.Selectable#6]
Hi. 
Thanks for that nice plugin.
Do you know that new Select extension [came to world](http://datatables.net/blog/2015-08-13#Select)? It seems that it duplicates functionality of Selectable.
What is your plans on it?

**Comment by toXXIc** [comment]
Hi! 
Thank you for letting me know!
I'm glad to hear that you like the plugin, but unfortunately right now I don't have enough time to spend on it. Sorry.

Also looking at DataTables.Select plugin I see that it provides even more features than Selectable plugin. So I think DT.Select is worth a try :)

**Comment by ashl1** [comment]
OK. Maybe a good idea to write in the Readme.md  to use DT.Select to notify developers about that?

**Comment by toXXIc** [comment]
Thanks, @ashl1. And sorry for the late reply. I added notification to Readme.md.
